name: Action to Generating Issues Markdown
on: [ push ]
jobs:
  generate_html:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: making kotlin script runnable
        run: chmod a+x ./script/playground.main.kts
      - name: Running Kotlin Script
        run: ./script/playground.main.kts
      - name: Commiting generated files
        run: |
          git config --local user.email "chetan.garg36@gmail.com"
          git config --local user.name "ch8n"
          git add .
          git commit -m "Automated Generated Issues Markdown"
      - name: Push Automated changes
      - uses: EndBug/add-and-commit@v7
        with:
          push: true

